config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint(8)        not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Cat < ApplicationRecord
  COLORS = %w(white black orange grey)
  SEX = ["M","F"]
  validates :birth_date, :name, :description, presence: true
  validates :color, inclusion: {in: COLORS}
   validates :sex, inclusion: {in: SEX}

  def age
    return "" if birth_date == nil
    now = Date.today
    now.year - birth_date.year
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
  protect_from_forgery prepend: true
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all
    render :index
  end


  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    now = Date.today
    date_of_birth = Date.parse((now.year - cats_params[:birth_date].to_i).to_s + '/01/01') unless cats_params[:birth_date].to_i < 0

    @cat = Cat.new(cats_params)
    @cat.update(birth_date: date_of_birth)

    if @cat.save
     redirect_to cat_url(@cat)
    else
      render json: @cat.errors.full_messages
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])
    @cat.update(cats_params)

    if @cat.save
     redirect_to cat_url(@cat)
    else
      render :edit
    end

  end

private
  def cats_params
    params.require(:cat).permit(:name,:color,:birth_date,:sex,:description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/_cat.html.erb
<table style="border: 1px solid black">
  <tr> <td>Name: </td> <td> <%= cat.name %></td> </tr>
  <tr> <td>Age:  </td> <td> <%= cat.age %></td> </tr>
  <tr> <td>Gender: </td> <td> <%= cat.sex %></td> </tr>
  <tr> <td>Color: </td> <td> <%= cat.color %></td> </tr>
  <tr> <td>Description: </td> <td> <%= cat.description %></td> </tr>
</table>

app/views/cats/edit.html.erb
<h2>Edit Cat</h2>

  <form action="<%=cats_url%>" method="POST">
    <input type="hidden" name="_method" value="patch">
  <label for="name">Name:
    <input id="name" type="text" name="cat[name]" value="<%= @cat.name %>">
  </label>
  <br>
  <label for="birth_date">Age:
    <input id="birth_date" type="text" name="cat[birth_date]" value="<%= @cat.birth_date %>">
  </label>
  <br>
  <label for="gender">Gender:
    <input id="sex" type="text" name="cat[sex]" value="<%= @cat.sex %>">
  </label>
  <br>
  <label for="color">Color:
    <input id="color" type="text" name="cat[color]" value="<%= @cat.color %>">
  </label>
  <br>
  <label for="description">Description:
    <input id="description" type="text" name="cat[description]" value="<%= @cat.description %>">
  </label>
  <br>
  <input type="submit" value="Update Cat">
</form>

app/views/cats/index.html.erb
<ul>
    <% @cats.each do |cat| %>
    <li>
    <%= render('cat', cat: cat) %>
    </li>
    <% end %>
</ul>

app/views/cats/new.html.erb
<h2>Create Cat</h2>

  <form action="<%=cats_url%>" method="POST">
  <label for="name">Name:
    <input id="name" type="text" name="cat[name]" value="<%= @cat.name %>">
  </label>
  <br>
  <label for="age">Age:
    <input id="age" type="text" name="cat[age]" value="<%= @cat.age %>">
  </label>
  <br>
  <label for="gender">Gender:
    <input id="sex" type="text" name="cat[sex]" value="<%= @cat.sex %>">
  </label>
  <br>
  <label for="color">Color:
    <input id="color" type="text" name="cat[color]" value="<%= @cat.color %>">
  </label>
  <br>
  <label for="description">Description:
    <input id="description" type="text" name="cat[description]" value="<%= @cat.description %>">
  </label>
  <br>
  <input type="submit" value="Create Cat">
</form>

app/views/cats/show.html.erb
<h2>Cat Information: </h2>
<%= render('cat', cat: @cat) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>